### ISSUE TITLE
can't open file 'train_controlnet_inpaint.py'

### ISSUE THREAD

**Issue by Jilin-Cancer** [yahoo/photo-background-generation#2]
Hi author, I'm very interested in your project, but when I ran the code from your readme, after I install requirements.txt , I couldn't find the “train_controlnet_inpaint.py” file

**Comment by erfaneshrati** [comment]
Hi @Jilin-Cancer ,

Thanks for catching the issue! We just corrected the training scripts filenames. You can learn more about training ControlNets at: https://github.com/huggingface/diffusers/tree/main/examples/controlnet.

"train_controlnet_inpaint.py" includes training codes of our proposed ControlNet architecture which uses the SD's inpainting UNet as ControlNet. "train_controlnet.py" is the same as the original implementation of ControlNet which uses the txt-to-image SD's UNet.
